version: '3.8'
services:
  web:
    build: .
    ports:
      - '8081:8081'
    environment:
      ONAIR_API_KEY: ${ONAIR_API_KEY}
      ONAIR_WORLD: ${ONAIR_WORLD}
      COMPANY_ID: ${COMPANY_ID}
      ONAIR_VA_ID: ${ONAIR_VA_ID}
    restart: unless-stopped
